const names = require('./3.5.2-fs')
const sayHiDiff = require('./3.5.3-fs')
require('./3.5.1-fs')
console.log(names)
//the below will use variables from names.js
sayHiDiff(names.my_name)
sayHiDiff(names.fish)
sayHiDiff(names.bowl)
sayHiDiff('Susan')
sayHiDiff("random name")